# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

  # Either `true` to make the repository private, or `false` to make it public.
  private: true

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: false

  # Either `true` to enable automatic deletion of branches on merge, or `false` to disable
  delete_branch_on_merge: false

  # Either `true` to enable automated security fixes, or `false` to disable
  # automated security fixes.
  enable_automated_security_fixes: true

  # Either `true` to enable vulnerability alerts, or `false` to disable
  # vulnerability alerts.
  enable_vulnerability_alerts: true

# Labels: define labels for Issues and Pull Requests
labels:
#   - name: bug
#     color: CC0000
#     description: An issue with the system 🐛.

#   - name: feature
#     # If including a `#`, make sure to wrap it with quotes!
#     color: '#336699'
    # description: New functionality.

# Milestones: define milestones for Issues and Pull Requests
milestones:
#   - title: milestone-title
#     description: milestone-description
#     # The state of the milestone. Either `open` or `closed`
#     state: open

# Collaborators: give specific users access to this repository.
# See https://docs.github.com/en/rest/reference/repos#add-a-repository-collaborator for available options
collaborators:
  # - username: bkeepers
  #   permission: push
  # - username: hubot
  #   permission: pull

  # Note: `permission` is only valid on organization-owned repositories.
  # The permission to grant the collaborator. Can be one of:
  # * `pull` - can pull, but not push to or administer this repository.
  # * `push` - can pull and push, but not administer this repository.
  # * `admin` - can pull, push and administer this repository.
  # * `maintain` - Recommended for project managers who need to manage the repository without access to sensitive or destructive actions.
  # * `triage` - Recommended for contributors who need to proactively manage issues and pull requests without write access.

# See https://docs.github.com/en/rest/reference/teams#add-or-update-team-repository-permissions for available options
teams:
  # - name: core
  #   # The permission to grant the team. Can be one of:
  #   # * `pull` - can pull, but not push to or administer this repository.
  #   # * `push` - can pull and push, but not administer this repository.
  #   # * `admin` - can pull, push and administer this repository.
  #   # * `maintain` - Recommended for project managers who need to manage the repository without access to sensitive or destructive actions.
  #   # * `triage` - Recommended for contributors who need to proactively manage issues and pull requests without write access.
  #   permission: admin
  # - name: docs
  #   permission: push

  
rulesets:
  - name: main
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - "refs/heads/main"
        exclude: []
    rules:
      - type: pull_request
        parameters:
          dismiss_stale_reviews_on_push: true
          require_code_owner_review: false
          require_last_push_approval: true
          required_approving_review_count: 1
          required_review_thread_resolution: false
      - type: non_fast_forward
      - type: deletion
  - name: UAT
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - "refs/heads/UAT"
        exclude: []
    rules:
      - type: pull_request
        parameters:
          dismiss_stale_reviews_on_push: true
          require_code_owner_review: false
          require_last_push_approval: true
          required_approving_review_count: 0
          required_review_thread_resolution: false
      - type: non_fast_forward
      - type: deletion
  - name: E2E
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - "refs/heads/E2E"
        exclude: []
    rules:
      - type: pull_request
        parameters:
          dismiss_stale_reviews_on_push: true
          require_code_owner_review: false
          require_last_push_approval: true
          required_approving_review_count: 0
          required_review_thread_resolution: false
      - type: non_fast_forward
      - type: deletion
      - type: required_linear_history